spring.application.name=gym-management-api
spring.profiles.active=local
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.customCssUrl=/swagger-ui-custom.css
springdoc.packages-to-scan=com.imanol.gym

app.jwt.secret=${JWT_SECRET:Z3ltLW1hbmFnZW1lbnQtYXBpLXNlY3JldC1rZXktZm9yLWRldmVsb3BtZW50}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}